'use strict';
// Builds a macOS .icns file from the PNG assets generated by generate-icon.js
const fs = require('fs');

// ICNS type codes for PNG-format icon entries (modern macOS)
const ENTRIES = [
  { size: 16,  type: 'icp4' },
  { size: 32,  type: 'icp5' },
  { size: 64,  type: 'icp6' },
  { size: 128, type: 'ic07' },
  { size: 256, type: 'ic08' },
  { size: 512, type: 'ic09' },
];

const chunks = [];
for (const { size, type } of ENTRIES) {
  const png  = fs.readFileSync(`assets/icon${size}.png`);
  const head = Buffer.alloc(8);
  head.write(type, 0, 'ascii');
  head.writeUInt32BE(8 + png.length, 4);
  chunks.push(Buffer.concat([head, png]));
}

const body   = Buffer.concat(chunks);
const header = Buffer.alloc(8);
header.write('icns', 0, 'ascii');
header.writeUInt32BE(8 + body.length, 4);

fs.writeFileSync('assets/icon.icns', Buffer.concat([header, body]));
console.log(`  ✓ assets/icon.icns (${((8 + body.length) / 1024).toFixed(1)} KB)`);
